### PR TITLE
announcement: Virtual FOSS Hours!

### PR DESCRIPTION
**Pull request by jwflory**
We're going virtual. :sunglasses: This just makes it official. #COVID19

Screenshot from local preview

### CODE REVIEW

**Comment by ritjoe** [comment]
I haven't found the Etherpad integration yet. What am I missing?

**Comment by jwflory** [comment]
@ritjoe Not sure I follow what you mean.

**Comment by ritjoe** [comment]
On Wed, Mar 18, 2020 at 06:52:16PM -0700, Joe wrote:
> 
> I haven't found the Etherpad integration yet. What am I missing?
>

I should say, that's the only snag I see. The rest looks good.

**Comment by jwflory** [comment]
I guess I don't follow where Etherpad connects with what you are asking for? :sweat_smile:

**Comment by ritjoe** [comment]
I've scrubbed around the interface looking for the Etherpad integration that is mentioned as a feature, but I'm not finding anything for it: No button or option or icon or whatever.

So, either it is missing in my browsers or I am overlooking it.

**Comment by jwflory** [comment]
Oh, whoops. I didn't read what I copy+pasted closely. :sweat_smile: Yeah I'm not sure about that either, I don't remember seeing Etherpad somewhere obvious in the Jitsi Meet interface!

**Comment by ritjoe** [comment]
On Wed, Mar 18, 2020 at 06:55:10PM -0700, jwflory wrote:
> I guess I don't follow where Etherpad connects with what you are asking for? 😅

+> What else can you do with Jitsi Meet?
+>
+> * Share your desktop, presentations, and more
+> * Invite users to a conference via a simple, custom URL
+> * Edit documents together using Etherpad
+> * Pick fun meeting URLs for every meeting


3rd item on the list. I'm focussing on that because collaborative document editing connected to a session would be a fun thing to try and potentially very useful, but I had not noticed it as a feature in my explorations to date. 

Seeing it listed here, I went looking for it but have not found it. Maybe I need to be logged in, or I need something else?

I realize that language is from their web site, and when I first saw it, it was not the top feature I was interested in.

I've tried recent Firefox (74.0). I think I've allowed All The Things via my uMatrix settings for the site. 

I've also tried Chromium, Version 80.0.3987.87 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

This sounds like a bug report more so than a review of our communication, but since that feature is listed prominently I'd like to know that what we're sending out matches with what we know it can do, I guess?

**Comment by ritjoe** [comment]
02:17 <@dzho> https://imh01-inmotionhosting1.netdna-ssl.com/support/images/stories/live-broadcasting/jitsi-meet-meeting-2.png <-- 
              screenshot shows "Open a shared document" between "Share a Youtube video" and "Settings"
02:17 <@dzho> but I do not see this in that same menu between those specific two items on current meet.jit.si sessions
02:18 <@dzho> so I think it is Not A Thing for meet.jit.si currently, though maybe it could still be configured for self-hosted 
              instances?


I guess just excising the line about Etherpad in the list of features would settle this for now.

**Comment by jwflory** [comment]
Thanks for the review @10eMyrT! Going to merge this in and get the word out. Also dropped the line about Etherpad that @ritjoe pointed out in commit 130c56a3db2737bbe662f6ce50cd36edda990375.

**Pull request merged**
